# Generated by Django 5.0.6 on 2024-07-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationdetails',
            old_name='skills',
            new_name='interested_domain',
        ),
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='verificationdetails',
            name='Describe_experience',
        ),
        migrations.RemoveField(
            model_name='verificationdetails',
            name='communication_skills',
        ),
    ]
