# Generated by Django 5.0.6 on 2024-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_personaldetails_language_keyskills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='uid',
        ),
        migrations.AddField(
            model_name='query',
            name='date_of_birth',
            field=models.DateField(default='2002-08-22'),
            preserve_default=False,
        ),
    ]
