# Generated by Django 5.0.6 on 2024-07-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_query_uid_query_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='email',
            field=models.EmailField(default='azhan@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
