# Generated by Django 5.0.6 on 2024-07-20 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resumelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addlink',
            name='url',
        ),
        migrations.RemoveField(
            model_name='language',
            name='proficiency_level',
        ),
        migrations.AddField(
            model_name='addlink',
            name='github_url',
            field=models.URLField(blank=True, help_text='Enter GitHub profile URL.', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='addlink',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Enter LinkedIn profile URL.', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900, message='Passing year cannot be before 1900.'), django.core.validators.MaxValueValidator(2024, message='Passing year cannot be in the future.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='resumelink',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
