# Generated by Django 5.0.6 on 2024-07-27 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_query_options_remove_query_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdetails',
            old_name='first_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='basicdetails',
            old_name='last_name',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='nationality',
            new_name='home_town',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='basicdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='email',
            field=models.EmailField(default='az@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='looking_for',
            field=models.CharField(choices=[('Internships', 'Internships'), ('Fresher Job', 'Fresher Jobs'), ('Experienced', 'Experienced Jobs')], default='Internships', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='whatsapp_number',
            field=models.CharField(default='999999999', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='education',
            field=models.CharField(default='12', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='marks',
            field=models.BigIntegerField(default='12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='current_company',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='CRTD', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='skill_used',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_environment',
            field=models.CharField(choices=[('On-Site', 'On-Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Remote', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='work_experience',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='ability',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='category',
            field=models.CharField(default='OBC', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='local_address',
            field=models.CharField(default='sdfsf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], default='2024-07-14T16:05:02.667150Z', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='permanent_address',
            field=models.CharField(default='sdsdfdsf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='pincode',
            field=models.IntegerField(default='462001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='safs', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2024-07-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('On-Going', 'On-Going')], default='Completed', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900, message='Passing year cannot be before 1900.'), django.core.validators.MaxValueValidator(2054, message='Passing year cannot be in the future.')]),
        ),
    ]
