# Generated by Django 5.0.6 on 2024-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_first_name_basicdetails_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fresherjob',
            name='code',
        ),
        migrations.RemoveField(
            model_name='fresherjob',
            name='code_required',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='code',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='code_required',
        ),
        migrations.AddField(
            model_name='fresherjob',
            name='about_company',
            field=models.CharField(default='CRTD', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='about_company',
            field=models.CharField(default='dasgdhgafgadfgh', max_length=255),
            preserve_default=False,
        ),
    ]
