# Generated by Django 5.0.6 on 2024-07-30 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_fresherjob_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlink',
            name='Others',
            field=models.URLField(blank=True, help_text='Enter Others profile URL.', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='addlink',
            name='Portfolio',
            field=models.URLField(blank=True, help_text='Enter Portfolio profile URL.', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='fresherjob',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default='2024-04-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fresherjob',
            name='work_environment',
            field=models.CharField(choices=[('On-Site', 'On-Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Remote', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='benifits',
            field=models.CharField(default='many', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default='2024-02-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='work_environment',
            field=models.CharField(choices=[('On-Site', 'On-Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Remote', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='applied_date',
            field=models.DateField(auto_now_add=True, default='2024-02-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(auto_now_add=True, default='2024-02-22'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='candidate_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Select', 'Select'), ('Shortlisted', 'Shortlisted'), ('Reject', 'Reject')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Select', 'Select'), ('Shortlisted', 'Shortlisted'), ('Reject', 'Reject')], max_length=20),
        ),
    ]
