# Generated by Django 5.0.6 on 2024-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_addlink_others_addlink_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresherjob',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='applied_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
