# Generated by Django 5.0.6 on 2024-07-31 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_fresherjob_knowledge_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('work_environment', models.CharField(choices=[('On-Site', 'On-Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('skills_required', models.CharField(max_length=255)),
                ('who_can_apply', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('about_company', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('CTC', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Experience Job',
                'verbose_name_plural': 'Experience Jobs',
            },
        ),
        migrations.CreateModel(
            name='ExperienceJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_status', models.CharField(choices=[('Applied', 'Applied'), ('Select', 'Select'), ('Shortlisted', 'Shortlisted'), ('Reject', 'Reject')], max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True, null=True)),
                ('experiencejob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='app.experience')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='app.register')),
            ],
            options={
                'verbose_name': 'Experience Job Application',
                'verbose_name_plural': 'Experience Job Applications',
            },
        ),
    ]
