# Generated by Django 5.0.6 on 2024-07-31 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_experiencejob_experiencejobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencejobapplication',
            name='experiencejob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='app.experiencejob'),
        ),
    ]
