# Generated by Django 5.0.6 on 2024-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_experiencejobapplication_experiencejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencejobapplication',
            name='years_experience',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
