# Generated by Django 5.0.6 on 2024-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_experiencejobapplication_years_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencejobapplication',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='experiencejob',
            name='years_experience_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fresherjob',
            name='years_experience_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='internship',
            name='years_experience_required',
            field=models.IntegerField(default=1),
        ),
    ]
