# Generated by Django 5.0.6 on 2024-07-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_experiencejobapplication_years_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fresherjob',
            name='years_experience_required',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='years_experience_required',
        ),
    ]
