# Generated by Django 5.0.6 on 2024-08-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_percentage_experiencejobapplication_current_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencejobapplication',
            name='current_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('Pass Out', 'Pass Out')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='current_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('Pass Out', 'Pass Out')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='current_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('Pass Out', 'Pass Out')], default=1, max_length=20),
        ),
    ]
