# Generated by Django 5.0.6 on 2024-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_experiencejobapplication_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresherjob',
            name='years_experience_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='internship',
            name='years_experience_required',
            field=models.IntegerField(default=1),
        ),
    ]
