# Generated by Django 5.0.6 on 2024-08-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_fresherjob_years_experience_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencejob',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='fresherjob',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='terms_and_conditions',
        ),
    ]
