# Generated by Django 5.0.6 on 2024-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_experiencejob_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='date_of_birth',
        ),
    ]
