# Generated by Django 5.0.6 on 2024-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_trainingprogram_alter_register_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='discount',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
    ]
