# Generated by Django 5.0.6 on 2024-09-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_trainingprogram_discount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingProgram',
        ),
    ]
