# Generated by Django 5.0.6 on 2024-09-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_trainingprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='payment_status',
            field=models.CharField(choices=[('Not Enroll', 'Not Enroll'), ('Enroll Pending', 'Enroll Pending'), ('Enrolled', 'Enrolled')], default='Not Enroll', max_length=15),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_details', to='app.register'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
