# Generated by Django 5.0.6 on 2024-09-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_trainingprogram_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='time_end',
        ),
    ]
