# Generated by Django 5.0.6 on 2024-09-28 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_trainingprogram_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='Discount as a percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
