# Generated by Django 5.0.6 on 2024-09-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_trainingprogram_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='register',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='time_end',
        ),
    ]
