# Generated by Django 5.0.6 on 2024-09-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_trainingprogram_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='original_price',
            field=models.PositiveIntegerField(),
        ),
    ]
