# Generated by Django 5.0.6 on 2024-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_trainingprogram_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
