# Generated by Django 5.0.6 on 2024-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_trainingprogram_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='program_includes',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='skills_you_will_gain',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_description',
            field=models.TextField(default='Not specified'),
        ),
    ]
