# Generated by Django 5.0.6 on 2024-09-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_trainingprogram_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='program_includes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='skills_you_will_gain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='training_description',
            field=models.TextField(),
        ),
    ]
