# Generated by Django 5.0.6 on 2024-09-30 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_trainingprogram_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgramApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FresherJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_details', to='app.fresherjob')),
                ('Register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_details', to='app.register')),
            ],
        ),
    ]
