# Generated by Django 5.0.6 on 2024-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_trainingprogramapplications_trainingprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramapplications',
            name='AppliedStatus',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Select', 'Select'), ('Pending', 'Pending'), ('Reject', 'Reject'), ('EXPIRE', 'EXPIRE'), ('DirectSelect', 'DirectSelect')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingprogramapplications',
            name='payment_status',
            field=models.CharField(choices=[('Not Enroll', 'Not Enroll'), ('Enroll Pending', 'Enroll Pending'), ('Enrolled', 'Enrolled')], default='Not Enroll', max_length=15),
        ),
        migrations.AddField(
            model_name='trainingprogramapplications',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
