# Generated by Django 5.0.6 on 2024-09-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_trainingprogramapplications_unique_registration_per_training'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingprogramapplications',
            name='unique_registration_per_training',
        ),
    ]
