# Generated by Django 5.0.6 on 2024-09-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_trainingprogramapplications_unique_registration_per_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogramapplications',
            name='AppliedStatus',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Select', 'Select'), ('Pending', 'Pending'), ('Reject', 'Reject'), ('EXPIRE', 'EXPIRE'), ('DirectSelect', 'DirectSelect')], max_length=50),
        ),
    ]
