# Generated by Django 5.0.6 on 2024-09-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_trainingprogramapplications_appliedstatus'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingprogramapplications',
            constraint=models.UniqueConstraint(fields=('Register', 'TrainingProgram'), name='unique_registration_per_training'),
        ),
    ]
