# Generated by Django 5.0.6 on 2024-09-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_trainingprogramapplications_unique_registration_per_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramapplications',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
