# Generated by Django 5.0.6 on 2024-09-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_trainingprogramapplications_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogramapplications',
            name='name',
        ),
    ]
