# Generated by Django 5.0.6 on 2024-09-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_trainingprogramapplications_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingProgramApplications',
        ),
    ]
