# Generated by Django 5.0.6 on 2024-09-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_delete_trainingprogramapplications'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.CharField(choices=[('Applied', 'Applied'), ('Not Applied', 'Not Applied')], default='Not Applied', max_length=20)),
                ('TrainingProgram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_details', to='app.trainingprogram')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_details', to='app.register')),
            ],
        ),
    ]
