# Generated by Django 5.0.6 on 2024-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_trainingprogramapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramapplication',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
