# Generated by Django 5.0.6 on 2024-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_trainingprogramapplication_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogramapplication',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='trainingprogramapplication',
            name='payment_status',
            field=models.CharField(choices=[('Not Enroll', 'Not Enroll'), ('Enroll Pending', 'Enroll Pending'), ('Enrolled', 'Enrolled')], default='Not Enroll', max_length=15),
        ),
        migrations.AddField(
            model_name='trainingprogramapplication',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
