# Generated by Django 5.0.6 on 2024-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_trainingprogramapplication_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='What_you_Will_learm',
            field=models.TextField(default=''),
        ),
    ]
