# Generated by Django 5.0.6 on 2024-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_trainingprogram_what_you_will_learm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='What_you_Will_learm',
            field=models.TextField(),
        ),
    ]
