# Generated by Django 5.0.6 on 2024-10-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_trainingprogram_what_you_will_learm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='program_includes',
        ),
    ]
